[package]
name = "xv6-labs-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "std_xv6"
crate-type = ["rlib"]
test = false
bench = false

[[bin]]
name = "hello"
test = false
bench = false

[dependencies]
no_std_io2 = { version = "0.8.1", features = ["alloc"] }
